### ISSUE TITLE
Not compatible with Kotlin Gradle build scripts

### ISSUE THREAD

**Issue by jonnyandrew** [bitrise-steplib/bitrise-step-android-unit-test#10]
Due to an issue with a dependency: https://github.com/bitrise-tools/go-android/issues/25 (resolved by https://github.com/bitrise-tools/go-android/pull/26 )

Fixed by updating the dependency - PR: https://github.com/bitrise-steplib/bitrise-step-android-unit-test/pull/9

**Comment by lpusok** [comment]
Closing as the dependency was updated (https://github.com/bitrise-steplib/bitrise-step-android-unit-test/pull/9#issuecomment-472902239).
