### ISSUE TITLE
Failed to fetch variants, error: Incremental java compilation is an incubating feature.

### ISSUE THREAD

**Issue by BobMuvaki** [bitrise-steplib/bitrise-step-android-unit-test#11]
Hi there,

I am having a bit of a problem. I get the following error during the android build

--------------------------------------------------------------------------------------------
Variants:
Failed to fetch variants, error: Incremental java compilation is an incubating feature.
FAILURE: Build failed with an exception.
* What went wrong:
A problem occurred configuring project ':app'.
> java.lang.NullPointerException (no error message)
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
---------------------------------------------------------------------------------------------

I tried the stacktrace option and it does not give me any extra information.

Please help.

**Comment by fehersanyi-bitrise** [comment]
Hello @BobMuvaki,
First of all, sorry for the late reply
Could you please send us this build's url, so we could check out the full logs for some more details and try to come up with a possible solution?

**Comment by BobMuvaki** [comment]
Hi @fehersanyi-bitrise 

Here it is:

https://app.bitrise.io/build/bdd53ed7409ff5e1

**Comment by fehersanyi-bitrise** [comment]
Could you try a build where you leave the module and the variant inputs empty?

**Comment by BobMuvaki** [comment]
Hi @fehersanyi-bitrise,

Thanks for your help. Updating gradle seems to have fixed the issue

Keep well.

**Comment by godrei** [comment]
I'll close this issue, but if you need more info/help just open a new issue!
