### ISSUE TITLE
Not working as it should

### ISSUE THREAD

**Issue by OleksandrKucherenko** [bitrise-steplib/bitrise-step-android-unit-test#2]
Details are in this ticket:

https://github.com/bitrise-io/steps-gradle-unit-test/issues/9#issuecomment-379672090

**Comment by trapacska** [comment]
Hey @OleksandrKucherenko!

The new version of the step([0.9.1](https://github.com/bitrise-steplib/bitrise-step-android-unit-test/releases/tag/0.9.1)) will be released soon. Please try it with the new version and please let us know if it fixes your issues.
