### ISSUE TITLE
Doesn't handle nested modules

### ISSUE THREAD

**Issue by ansman** [bitrise-steplib/bitrise-step-android-unit-test#20]
We have a nested module (`:a` and `:a:b`) which this step fails to recognize so it only runs the tests in `:a`.

**Comment by bitce** [comment]
Hi @ansman! 

Sorry for the delay, but thanks for your report! Can you perhaps send us a build URL as an example of this happening?

**Comment by ansman** [comment]
Here's an example, the module `:network:interceptor` is not included: https://app.bitrise.io/build/57673d0dd416b9e1

**Comment by HugoAlberto** [comment]
I did found a way to fix the issue, I simply cloned this bitrise step and uploaded it to a public repo.
I wanted to invastigate the problem but found it was already fixed. A new release with the current code will, I think, fix the issue.

**Comment by Roland-Bak** [comment]
Hi there,

Thanks for sharing the helpful info, @HugoAlberto! You're right, a permanent fix is still in the works, but should make this issue go away for good 🙂
