### ISSUE TITLE
Tests won't be run on SDK 29 unless explicitly requested

### ISSUE THREAD

**Issue by whck6** [bitrise-steplib/bitrise-step-android-unit-test#23]
How to fix it?

> [Robolectric] WARN: Android SDK 29 requires Java 9 (have Java 8). Tests won't be run on SDK 29 unless explicitly requested.

**Comment by istx25** [comment]
Hi @whhotw,

Thank you for reaching out.

Can you please share a link to a build link that reproduces this and enable support access?
